function realizations = edgeRealizations(edge)
%EDGEREALIZATIONS creates all possible realizations of an edge for future
%comparison.

realizations = [edge NaN;...
                NaN edge;...
                edge(2) NaN edge(1);...
                flip(edge) NaN;...
                NaN flip(edge);...
                edge(1) NaN edge(2)];



end

